# Generated by Django 3.2.13 on 2022-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=52)),
            ],
        ),
    ]
