# Generated by Django 3.1 on 2022-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT/VOICEACTRESS100_012.wav', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
