# Generated by Django 3.2.13 on 2022-07-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsapp', '0002_auto_20220716_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
